Frontend
wiktorkisielewski/helbreder pull request #2
Opened 2022-09-06 19:10 UTC by witkiewiczmikolaj

Frontend changes

2022-09-07 05:28 UTC, wiktorkisielewski requested changes

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/app.py
> +import yaml
any `lib` used here must be referenced in [requirements.txt](https://github.com/wiktorkisielewski/helbreder/blob/main/core/requirements.txt) as these are the libs installed in docker, please add it there with the desired version number

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/app.py
> +    kubernetes = list(data['modules'].keys())[0].title()
this is a kind of a bad pattern, unfortunately, it won't scale as this app grows

Imagine there is more than 2 sections/modules, image there are 8945943659 of them - would you still code each of them here?

I think you should create a separate function that will 'load' data from `possibilities.yml` and use it to generate this (in some kind of loop for ex.)

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/app.py
> +    server = list(data['modules'].keys())[1].title()
same as line 15 
it wont scale

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/app.py
> +    act = "Choose an action:"
again, a variable that is badly named, declared and referenced just one == it is unnecessary

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/app.py
> +    action3 = data['modules'][f'{action}']['actions'][2].title()
kind of the same story as in line 15, imagine there are 89459236594 possible actions

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/app.py
> +    target3 = data['modules'][f'{target}']['targets'][2].title()
I guess you already know, but just in case -> same as line 15 and 28

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/static/css/main.css
> +@media screen and (max-width: 600px) {
responsive approach <3

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/static/css/main.css
> +    font-size: 30px;
I think it is better to reference dimensions (fonts, borders, button size, etc..) in `rem/em` or `vw/vh`, however it looks like this should be a problem in browsers newer than IE7 (see link below), so this is up to you 👍 
(I am okay with anything that will be displayed properly both on mobile and desktop devices)

https://stackoverflow.com/a/11803273/19884911

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/templates/index.html
> +        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
I think the same could be achieved in pure `flask/python` environment -> [flask button actions](https://thewebdev.info/2022/04/02/how-to-call-a-python-flask-function-on-button-click-event/)

It would be desired to not use `ajax/js` if not necessary 

Try to keep this whole code "stupid simple" and consistent

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/templates/actions.html
> +    <button class="act_butt" id="butt4" type="button">{{ action3 }}</button>
Think of a way of dynamically generating this -> for example create a flask function with a small `html` snippet, and use it to add buttons in a loop

Once again, imagine you have 82492763 possible actions and want a button for everything

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/templates/index.html
> +                <button class="welc_butt" id="butt" type="button">{{ kubernetes }}</button>
see comment associated with `actions.html` -> same applies here

(what if there are 872498387 modules?)

2022-09-07 05:28 UTC, wiktorkisielewski commented on core/templates/targets.html
> +    <button class="targ_butt" id="butt5" type="button">{{ target1 }}</button>
see comment in `actions.html`

2022-09-08 20:00 UTC, witkiewiczmikolaj commented on core/app.py
> +    with open(os.path.abspath("D:/helbreder/doc/possibilities.yml"), 'r') as stream:
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/485e431a25d59ef4fa07db24a7d749ab987b87ad

2022-09-08 20:01 UTC, witkiewiczmikolaj commented on core/app.py
> +    welc = "Choose a module:"
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/485e431a25d59ef4fa07db24a7d749ab987b87ad

2022-09-08 20:02 UTC, witkiewiczmikolaj commented on core/templates/index.html
> +        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
Resloved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/485e431a25d59ef4fa07db24a7d749ab987b87ad

2022-09-08 20:11 UTC, witkiewiczmikolaj commented on core/app.py
> +import os
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/485e431a25d59ef4fa07db24a7d749ab987b87ad

2022-09-08 20:11 UTC, witkiewiczmikolaj commented on core/app.py
> +    with open(os.path.abspath("D:/helbreder/doc/possibilities.yml"), 'r') as stream:
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/485e431a25d59ef4fa07db24a7d749ab987b87ad

2022-09-08 20:11 UTC, witkiewiczmikolaj commented on core/app.py
> +    with open(os.path.abspath("D:/helbreder/doc/possibilities.yml"), 'r') as stream:
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/485e431a25d59ef4fa07db24a7d749ab987b87ad

2022-09-08 20:12 UTC, witkiewiczmikolaj commented on core/app.py
> +import yaml
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/485e431a25d59ef4fa07db24a7d749ab987b87ad

2022-09-08 20:13 UTC, witkiewiczmikolaj commented on core/app.py
> +    act = "Choose an action:"
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/485e431a25d59ef4fa07db24a7d749ab987b87ad

2022-09-08 20:13 UTC, witkiewiczmikolaj commented on core/templates/targets.html
> +    <button class="targ_butt" id="butt5" type="button">{{ target1 }}</button>
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/485e431a25d59ef4fa07db24a7d749ab987b87ad

2022-09-11 09:15 UTC, witkiewiczmikolaj commented on core/templates/actions.html
> +    <button class="act_butt" id="butt4" type="button">{{ action3 }}</button>
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/c5e1a99789736c74f2da7e1e1a58ceaf18000739

2022-09-11 09:15 UTC, witkiewiczmikolaj commented on core/templates/index.html
> +                <button class="welc_butt" id="butt" type="button">{{ kubernetes }}</button>
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/c5e1a99789736c74f2da7e1e1a58ceaf18000739

2022-09-11 09:15 UTC, witkiewiczmikolaj commented on core/app.py
> +    kubernetes = list(data['modules'].keys())[0].title()
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/c5e1a99789736c74f2da7e1e1a58ceaf18000739

2022-09-11 09:16 UTC, witkiewiczmikolaj commented on core/app.py
> +    server = list(data['modules'].keys())[1].title()
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/c5e1a99789736c74f2da7e1e1a58ceaf18000739

2022-09-11 09:16 UTC, witkiewiczmikolaj commented on core/app.py
> +    action3 = data['modules'][f'{action}']['actions'][2].title()
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/c5e1a99789736c74f2da7e1e1a58ceaf18000739

2022-09-11 09:16 UTC, witkiewiczmikolaj commented on core/app.py
> +    target3 = data['modules'][f'{target}']['targets'][2].title()
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/commit/c5e1a99789736c74f2da7e1e1a58ceaf18000739

2022-09-11 10:34 UTC, merged

2022-09-11 12:27 UTC, wiktorkisielewski reviewed
nice!

2022-09-11 12:29 UTC, wiktorkisielewski reviewed
(y)

2022-09-11 12:30 UTC, wiktorkisielewski reviewed
im proud

2022-09-11 12:31 UTC, wiktorkisielewski reviewed
👍

2022-09-11 12:32 UTC, wiktorkisielewski reviewed
.