Frontend v2
wiktorkisielewski/helbreder pull request #3
Opened 2022-09-13 12:58 UTC by witkiewiczmikolaj

2022-09-13 17:41 UTC, wiktorkisielewski requested changes

2022-09-13 17:41 UTC, wiktorkisielewski commented on core/app/app.py
> +    global butt_clicked
this should be declared right at the begging of the function, for example :
```
def myfunc():
  global x
  x = "fantastic"
```
if you use `global `in the middle of the function it makes the variable available only for part of it, which may lead to misbehaviors

2022-09-13 17:41 UTC, wiktorkisielewski commented on core/app/app.py
> +    user_pass = 'user:pass'
`user` and `pass(word)` should be two separate variables :p
I think you misunderstood my example

2022-09-13 17:41 UTC, wiktorkisielewski commented on core/app/app.py
> +    return render_template('index.html', module = module, action = action, target = target, butt_clicked = butt_clicked, user_pass = user_pass)
`butt_clicked` 
(‿ˠ‿)

2022-09-13 17:41 UTC, wiktorkisielewski commented on core/app/templates/index.html
> +                <div class="cm-linerow"><span class="cm-lineNumber">15</span><span class="cm-variable">response</span>=&nbsp;<span style="color:#f07178;">requests</span>.<span style="color:#C792EA;">
What if it is longer than 15 lines?
https://curlconverter.com/java/ <- test the `curl` request here

It would be  desired to prepare the request in the backend (python) and then render the necessary number of lines

That is a really bad pattern and won't scale

2022-09-13 17:41 UTC, wiktorkisielewski commented on core/app/templates/index.html
> +        <div id="playgr_shell" style="display: block;" class="playground_shell">
Instead of creating a `div` for every language, try to make one universal `div` and use it with parameter/variables

2022-09-13 17:41 UTC, wiktorkisielewski commented on core/app/templates/index.html
> +            function showShell() {
`javascript` is just as unwanted here as `ajax`, try to keep this app as simple as possible - don't add new languages

and **there is no javascript in our docker image** so it won't even work

2022-09-13 17:41 UTC, wiktorkisielewski commented on core/app/templates/post.py
> +        user_pass = str(base64.b64encode(user_pass.encode("utf-8")))[2:-1]
`base64.b64encode(user_pass.encode("utf-8")).decode("utf-8")`
Hardcoding parts of the string to be cut out is risky and not elegant, it can be easily decoded to string :)

2022-09-15 18:06 UTC, witkiewiczmikolaj commented on core/app/app.py
> +    global butt_clicked
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/pull/3/commits/28f4966406551a1b4cfe8e669d7956897afeefcd

2022-09-15 18:07 UTC, witkiewiczmikolaj commented on core/app/app.py
> +    user_pass = 'user:pass'
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/pull/3/commits/28f4966406551a1b4cfe8e669d7956897afeefcd

2022-09-15 18:07 UTC, witkiewiczmikolaj commented on core/app/app.py
> +    return render_template('index.html', module = module, action = action, target = target, butt_clicked = butt_clicked, user_pass = user_pass)
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/pull/3/commits/28f4966406551a1b4cfe8e669d7956897afeefcd

2022-09-15 18:07 UTC, witkiewiczmikolaj commented on core/app/templates/index.html
> +                <div class="cm-linerow"><span class="cm-lineNumber">15</span><span class="cm-variable">response</span>=&nbsp;<span style="color:#f07178;">requests</span>.<span style="color:#C792EA;">
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/pull/3/commits/28f4966406551a1b4cfe8e669d7956897afeefcd

2022-09-15 18:07 UTC, witkiewiczmikolaj commented on core/app/templates/index.html
> +        <div id="playgr_shell" style="display: block;" class="playground_shell">
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/pull/3/commits/28f4966406551a1b4cfe8e669d7956897afeefcd

2022-09-15 18:07 UTC, witkiewiczmikolaj commented on core/app/templates/post.py
> +        user_pass = str(base64.b64encode(user_pass.encode("utf-8")))[2:-1]
Resolved in commit:
https://github.com/wiktorkisielewski/helbreder/pull/3/commits/28f4966406551a1b4cfe8e669d7956897afeefcd

2022-09-15 18:08 UTC, witkiewiczmikolaj commented on core/app/templates/index.html
> +            function showShell() {
Javascript stays

2022-09-16 06:10 UTC, wiktorkisielewski requested changes
imporve post.py

2022-09-16 06:10 UTC, wiktorkisielewski commented on core/app/templates/post.py
> +    if request.form.get("Shell") == "Shell" or \
this is once again not a scalable approach - maybe create a file with the list of languages (YAML preferably) and try to load it and use it just like possibilities. Make adding new language as simple as adding a new line to that file and png logo

Bellow code should be helpful ;)
```
>>> for lang in langs:
...     if request_form(lang) == lang:
...             print('matched')
...             break
...
matched
```

2022-09-16 06:10 UTC, wiktorkisielewski commented on core/app/templates/post.py
> +    if request.form.get("Shell") == "Shell":
avoid hardcoding identical parts of code (like this), load the languages from some file -> make a loop or a template function for that `if statement`

2022-09-16 06:10 UTC, wiktorkisielewski commented on core/app/templates/post.py
> +                button_clicked[2] = request.form.get(f'{targets(modules()[module])[targ].title()}')
almost a mirrored loops (from line 23) -> create a function/class/module/file and use it with parameters (this will keep the code cleaner)

2022-09-16 06:10 UTC, wiktorkisielewski commented on core/app/templates/post.py
> +        button_clicked[3] = username
`button_clicked[3] = base64.b64encode((request.form.get("Username")).encode("utf-8"))`
☝️ 3 lines squeezed into one with the same effect, yet it is not a good approach (but better that define same var 3 times)

You are doing same thing with `password` and `username` -> so create a separate function for this and return the desired value from it

2022-09-16 06:10 UTC, wiktorkisielewski commented on core/app/templates/post.py
> +        username = 'username'
this var is defined in `44` line, why do you overwrite it here?

2022-09-20 17:30 UTC, wiktorkisielewski approved these changes

2022-09-20 17:40 UTC, wiktorkisielewski approved these changes
nice :)

2022-09-20 17:40 UTC, merged