Frontend v3
wiktorkisielewski/helbreder pull request #6
Opened 2022-09-22 08:04 UTC by witkiewiczmikolaj

2022-09-22 08:45 UTC, wiktorkisielewski requested changes

2022-09-22 08:45 UTC, wiktorkisielewski commented on core/app/app.py
>  @helbreder.route('/code')
please define what requests are allowed here:
`@helbreder.route('/code', methods=['???'])`

2022-09-22 08:45 UTC, wiktorkisielewski commented on core/app/app.py
> +    except:
what `exception` is expected here?
it **must be defined**

2022-09-22 08:58 UTC, witkiewiczmikolaj commented on core/app/app.py
>  @helbreder.route('/code')
Resolved in commit: https://github.com/wiktorkisielewski/helbreder/pull/6/commits/ba6649d844725a3c9eb455619b7bb156fc70e920

2022-09-22 08:58 UTC, witkiewiczmikolaj commented on core/app/app.py
> +    except:
Resolved in commit: https://github.com/wiktorkisielewski/helbreder/pull/6/commits/ba6649d844725a3c9eb455619b7bb156fc70e920

2022-09-23 14:29 UTC, wiktorkisielewski approved these changes

2022-09-23 14:29 UTC, wiktorkisielewski commented on core/app/templates/sql.py
> +    c.close()
nice

2022-09-23 19:53 UTC, merged